FROM apache/airflow:3.2.2-python3.12

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io \
    && rm -rf /var/lib/apt/lists/* \
    && usermod -aG docker airflow

USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-docker \
    boto3 \
    mlflow
